export enum LookupsEndPoints{
  'empreendimentoId'= '/cadastros/Lookups/Empreendimentos',
  'motivoId' = '/suprimentos/Lookups/Motivos',
  'ofDescontoMaterial'= '/suprimentos/Lookups/OFsDescontoMaterial',
  'aprovador'='/cadastros/Lookups/Usuarios',
  'empresaId' = '/cadastros/Lookups/Empresas',
  'planoContasId' = '/cadastros/Lookups/PlanoContasDespesas',
  'servicoId' ='/contratoservicos/Lookups/Servicos',
  'insumoId'='/suprimentos/Lookups/Insumos',
  'insumoSubstituicaoId'='/suprimentos/Lookups/Insumos',
  'blocoId' = '/cadastros/Lookups/Blocos',
  'unidadeId'= '/cadastros/Lookups/Unidades',
  'etapaId' = '/orcamentos/Lookups/Etapas',
  'EmpresasDoEmpreendimento' = '/cadastros/Lookups/EmpresasDoEmpreendimento',
  'ordemServicoId' = '/frotas/Lookups/OrdemServico',
  'equipamentoId'='/frotas/Lookups/Equipamentos',
  'colaboradorCod' = '/cadastros/Lookups/Pessoas',
  'equipamentoemprdtermo' = '/frotas/Lookups/EquipamentoDisponiveisEmpreendimentoTermoResp',
  'insumoEmEstoque' = '/suprimentos/Estoque/InsumosEmEstoque'
}
